//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDataAccesss
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sinh_Vien
    {
        public string MSV { get; set; }
        public string Lop { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string Ho { get; set; }
        public string Ten { get; set; }
    }
}
