//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiCRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nguoi_Dung
    {
        public int MaND { get; set; }
        public string TK { get; set; }
        public string MK { get; set; }
    }
}
